---
include:
  - board: seeeduino_xiao_ble
    shield: smatrix_left rgbled_adapter
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: smatrix_right rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: settings_reset